[pytest]
addopts = -v -s --alluredir=reports/allure-results
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    auth: marks tests as part of the authentication module
    dashboard: marks tests as part of the dashboard module
    workout: marks tests as part of the workout module
    ai: marks tests as part of the AI detection module
    smoke: marks tests as smoke tests
    regression: marks tests as regression tests
