name: k6 Load Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual trigger from GitHub UI
    inputs:
      target_url:
        description: 'URL to load test'
        required: true
        default: 'https://google.com'

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run k6 Load Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: load-testing/baseline.js
        env:
          TARGET_URL: ${{ github.event.inputs.target_url || 'https://google.com' }}
